#include "system.h"
#include "types.h"
#include "asm.h"
#include "msxdos.h"
#include "string.h"
#include "stdio.h"


static Z80_registers regs;
fileInfoBlock fib;


bool MsxDos2IsRunning()
{
    DosCall(F_DOSVER, &regs, REGS_MAIN, REGS_MAIN);
    return regs.Bytes.A == 0 && regs.Bytes.B >= 2;
}


void TerminateWithErrorCode(byte errorCode)
{
    regs.Bytes.B = errorCode;
    DosCall(F_TERM, &regs, REGS_MAIN, REGS_NONE);
    //Fallback in case we are in MSX-DOS 1
    DosCall(F_TERM0, &regs, REGS_NONE, REGS_NONE);
}


byte NormalizeDirectory(char* directoryPath, char* normalizedDirectoryPath)
{
    char* pointer;

    // First append "\" to the directory path, unless it already has it
    // or the path has the form "X:" (meaning "current directory of drive X").
    // That way we tell DOS that we expect the path to be a directory.

    strcpy(normalizedDirectoryPath, directoryPath);
    pointer = normalizedDirectoryPath + strlen(normalizedDirectoryPath) - 1;
    if(pointer[0] != '\\' && pointer[0] != ':')
    {
        pointer[1] = '\\';
        pointer[2] = '\0';
    }

    // Then invoke _FFIRST, and if we get no error or .NOFIL Then
    // we're good to go (the later means that the directory is empty).
    // Otherwise we'll typically get "Invalid drive", "Invalid path"
    // or "Directory not found".

    regs.Words.DE = (int)normalizedDirectoryPath;
    regs.Bytes.B = 0;
    regs.Words.IX = (int)&fib;
    DosCall(F_FFIRST, &regs, REGS_ALL, REGS_MAIN);

    if(regs.Bytes.A != 0 && regs.Bytes.A != ERR_NOFIL)
        return regs.Bytes.A;

    // Now _WPATH will give us the normalized directory, we just need to
    // prepend the drive (which we can get from the FIB generated by _FFIRST).

    normalizedDirectoryPath[0] = fib.logicalDrive + 'A' - 1;
    normalizedDirectoryPath[1] = ':';
    normalizedDirectoryPath[2] = '\\';

    regs.Words.DE = (int)normalizedDirectoryPath + 3;
    DosCall(F_WPATH, &regs, REGS_MAIN, REGS_MAIN);

    // Lastly, we need to remove the "????????.???" that _WPATH appends
    // at the end of the normalized path (_WPATH returns HL pointing to it)

    pointer = (char*)regs.Words.HL;
    if(pointer[0] == '?')
    {
        pointer[0] = '\0';
    }

    return 0;
}